name: next-init

on:
  workflow_dispatch:

jobs:
  create-next-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cleanup
      run: |
        shopt -s extglob
        find . -mindepth 1 ! -path "./.github*" ! -name "tisf.json" -exec rm -rf {} +

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the version of Node.js you prefer

    - name: Create App
      run: npx -y create-next-app@latest nextapp --ts --skip-install --eslint --no-tailwind --no-src-dir --app --turbopack --no-import-alias

    - name: Move app to root
      run: |
        shopt -s dotglob
        mv nextapp/* .
        rmdir nextapp

    - name: Commit changes
      run: |
        git init
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Set up React Native app with create-expo-app'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
